version: '3'
services:
#  app:
#    build: .
#    image: app:1.0
#    container_name: app
#    ports:
#      - '8080:8080'
#    depends_on:
#      - postgres

  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    ports:
      - '5432:5432'
    volumes:
      - $PWD/data:/var/lib/postgres




